### ISSUE TITLE
Compute helm chart. Which services must be run?

### ISSUE THREAD

**Issue by roman-shakudo** [neondatabase/helm-charts#94]
Hi

I managed to run neon on my k8s cluster based on https://github.com/neondatabase/helm-charts/issues/35
![Image](https://github.com/user-attachments/assets/9eabf104-ad65-4297-acee-abaac4758ee6)

I see pageserver and three safekeepers running
I had to force using k8s service dns as BROKER_ENDPOINT and S3_ENDPOINT because default values are not correct

Since I was changing charts manually pageserver and safekeeper added dependecies which were run as dependant charts

Storage controller is falling with Error: loading public key. I suppose JWT issue
Storage Scrubber's image is not available

Questions:
1. Am I understand right that we have to wait for Compute chart? AFAIK I can't use any posgtres
2. Which services are essential to run neon? I see a lot of various services and I do not know which are core. It would great to add some doc about it
3. How can deployment be tested?
4. Can I pack Compute from docker-compose.yaml in neon as a helm cart and use it or this image is just for "testing"?
5. Am I understand right that there is no UI in the helm charts?

**Comment by roman-shakudo** [comment]
From docs I could figure out that the core services are
* pageserver
* safekeeper
* compute
* storage broker
* storage controller
* minio (for local or k8s)

Have no idea what others are
* pn-sni-router
* proxy
* storage-scrubber

And the whole architecture is kinda like that
![Image](https://github.com/user-attachments/assets/e9dccc1b-8733-4239-8b27-666952f5c0f9)

**Comment by GangWangAI** [comment]
I wrote a compute chart that runs normally for about 6 minutes before crashing and automatically restarting. The error log shows: 

```
PG:2024-11-05 09:48:58.052 GMT [69] PANIC:  [WP] collected propEpochStartLsn 0/1537150, but basebackup LSN 0/14EE288
PG:2024-11-05 09:48:58.053 GMT [43] LOG:  background worker "WAL proposer" (PID 69) was terminated by signal 6: Aborted
PG:2024-11-05 09:48:58.053 GMT [43] LOG:  terminating any other active server processes
```

**Comment by roman-shakudo** [comment]
[GangWangAI](https://github.com/GangWangAI)
I did not run it
Somewhere I found information that k8s chart is not priority right now and was told to use cloud one =)

Related Compute node
Did you apply patches neondb team created for a potstgres mentioned [here](https://github.com/neondatabase/neon?tab=readme-ov-file#building-on-linux)?

**Comment by jcsp** [comment]
We'e clarified the README to explain that the helm charts are currently not meant to bring up a full working system: they just represents the components where we at Neon use helm at present: https://github.com/neondatabase/helm-charts/pull/119

I think this issue refers to safekeeper/pageserver patches from https://github.com/neondatabase/helm-charts/issues/35, so I'm going to close this one in favor of that one -- let's use that one as a place for folks to collaborate when they would like to try bringing up fully working systems via helm
